[build]

command = "npm run build"
publish="https://github.com/MarwanKhan-design/react_tempreture_app/build"
base = "https://github.com/MarwanKhan-design/react_tempreture_app"

[redirects]

form = "/*"
to = "/index.html"
status = 200